name: Dependencies

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  cache-dependencies:
    name: Cache Global Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-

      - name: Cache cargo git index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-git-

      - name: Fetch and cache Rust dependencies
        run: cargo fetch --locked

      - name: Verify cache contents
        run: |
          echo "Cargo registry size:"
          du -sh ~/.cargo/registry || echo "Registry not found"
          echo "Cargo git index size:"
          du -sh ~/.cargo/git || echo "Git index not found"
          echo "Dependencies cached successfully!"
