name: Nightly Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: Code Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install nightly Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: Check formatting
        id: fmt
        continue-on-error: true
        run: |
          if ! cargo +nightly fmt --all -- --check; then
            echo "::warning::Code formatting issues detected. Run 'cargo +nightly fmt --all' to fix."
            exit 1
          fi

      - name: Generate formatting summary
        if: always()
        run: |
          echo "## 🎨 Code Formatting" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.fmt.outcome }}" = "success" ]; then
            echo "✅ All code is properly formatted" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ Code formatting issues detected" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "To fix formatting issues, run:" >> $GITHUB_STEP_SUMMARY
            echo '```bash' >> $GITHUB_STEP_SUMMARY
            echo "cargo +nightly fmt --all" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
